name: "Multi event pipeline / workflow"


on: 
    push: # Event: Whenever a push is made to the repository on the master branch
      branches:
        - main
        - prod


jobs: 
    on-push: # Job name 
        runs-on: ubuntu-latest
        steps:  # steps to be executed in the job 
            - name: "Running on master push" # step 1
              run: echo "Running on main push"

