name: "Multi event pipeline / workflow"


on: 
    push: # Event: Whenever a push is made to the repository on the master branch
      branches:
        - main
        - test
    pull_request: # Event: Whenever a pull request is made to the repository 
      branches:
        - main
      types: 
        - closed 
    # on closed the pr on branch main this workflow will run

    workflow_dispatch: 


jobs: 
    on-push: # Job name 
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:  # steps to be executed in the job 
            - name: "Running on master push" # step 1
              run: echo "Running on main push"

    on-pull-request: # job name 
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on pull request"
              run: echo "Running on pull request"

    on-pull-request-closed: 
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"


    on-workflow-dispatch: 
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on workflow dispatch"
              run: echo "Running on workflow dispatch"

